services:
  - type: web
    name: crew-data-capture
    env: node
    repo: https://github.com/your-username/crew-data-capture # Reemplaza con tu repo
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
    healthCheckPath: /
